require('util.map')
nmap('SS', '<Plug>YSsurround', true)
nmap('Ss', '<Plug>YSsurround', true)
nmap('ss', '<Plug>Yssurround', true)
nmap('S', '<Plug>YSurround', true)
nmap('s', '<Plug>Ysurround', true)
