require('util.map')
Nmap('SS', '<Plug>YSsurround', true)
Nmap('Ss', '<Plug>YSsurround', true)
Nmap('ss', '<Plug>Yssurround', true)
Nmap('S', '<Plug>YSurround', true)
Nmap('s', '<Plug>Ysurround', true)
