vim.keymap.set('n', 'SS', '<Plug>YSsurround', { silent = true })
vim.keymap.set('n', 'Ss', '<Plug>YSsurround', { silent = true })
vim.keymap.set('n', 'ss', '<Plug>Yssurround', { silent = true })
vim.keymap.set('n', 'S', '<Plug>YSurround', { silent = true })
vim.keymap.set('n', 's', '<Plug>Ysurround', { silent = true })
